export const UPDATE_CONNECTED_DEVICE = 'UPDATE_CONNECTED_DEVICE';
export const DISCONNECT_DEVICE = 'DISCONNECT_DEVICE';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
